logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
spring:
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
